name: simple_widget_markup
description: This is an option that allows you to statically create layouts.
version: 46.0.2
repository: https://github.com/MasahideMori-SimpleAppli/simple_widget_markup

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  simple_block_markup_language: ^3.3.1
  simple_managers: ^7.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_lint: ^2.0.0